### ISSUE TITLE
is there any plan for hardware implementation

### ISSUE THREAD

**Issue by iceberg1369** [globsky/greta-oto#8]
I would like to know if there is a plan for hardware implementation? if yes, what do you suggest for hardware architecture?

**Comment by globsky** [comment]
My plan is to find a partner and tape out a SoC chip as hardware implementation platform. The SoC will have RF and MCU included. Currently, a GNSS RF + FPGA will also be OK.

**Comment by iceberg1369** [comment]
Any update on this?
