### ISSUE TITLE
Change doppler range

### ISSUE THREAD

**Issue by iceberg1369** [globsky/greta-oto#9]
Where is paramaters to change doppler from 5khz to 10khz for example

**Comment by globsky** [comment]
The baseband process hardware does not have any limitation on Doppler range. Could you give a more specific description on where will you need to set Doppler range?

**Comment by iceberg1369** [comment]
I need to plot code phase vs doppler and I need to narrow down doppler range. Eg 2khz for the sake of less computing power

**Comment by globsky** [comment]
If what you are asking is the acquisition engine search range, you can find it at line 140 of FirmwarePortal.c: "AcqConfig.StrideNumber = 19;", which gives +-5kHz search range. Actually, the Doppler comes from the signal source, so reduce the range may cause some satellite failed to be acquired.
